Repository jenkins-x-plugins/jx-project, pull requests merged in 2020-09, with the labels that each got.

#34 fix: add workaround for the preview folder
  Dockerfile
  Dockerfile-preview
  jenkins-x.yml
  pkg/cmd/importcmd/import_golang_integration_test.go
  pkg/cmd/importcmd/pack.go
Labels: approved, size/S

#37 fix: CI
  pkg/cmd/root/quickstart.go
Labels: approved, size/XS

#38 fix: upgrade deps
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
Labels: approved, size/S

#40 fix: upgrade and auto trigger pipelines on create
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_deploy_integration_test.go
  pkg/cmd/importcmd/import_github_action_integration_test.go
  pkg/cmd/importcmd/import_gitops_repo_test.go
  pkg/cmd/importcmd/import_golang_integration_test.go
  pkg/cmd/importcmd/import_integration_test.go
  pkg/cmd/importcmd/import_kube_resources_integration_test.go
  pkg/cmd/importcmd/import_test.go
  pkg/cmd/root/quickstart_integration_test.go
  pkg/cmd/testimports/fakes.go
Labels: approved, size/L

#41 fix: add wait argument when starting a pipeline
  pkg/cmd/importcmd/import.go
Labels: approved, size/XS

#42 fix: ensure we have created the git client
  pkg/cmd/root/pullrequest/create_pullrequest.go
Labels: approved, size/XS

#43 fix: jx project pr command
  pkg/cmd/root/pullrequest/create_pullrequest.go
Labels: approved, size/XS

#44 fix: pass through the git commit title/body
  pkg/cmd/root/pullrequest/create_pullrequest.go
Labels: approved, size/XS

#45 fix: add more diagnostics
  pkg/cmd/root/pullrequest/create_pullrequest.go
Labels: approved, size/XS

#47 fix: use debug logging by default
  go.mod
  go.sum
  pkg/cmd/root/pullrequest/create_pullrequest.go
Labels: approved, size/M

#50 chore(doc): Add notice about git credentials file used when no github username or token is specified
  docs/cmd/project_import.md
  docs/cmd/project_quickstart.md
  docs/cmd/project_spring.md
  docs/man/man1/project-import.1
  docs/man/man1/project-quickstart.1
  docs/man/man1/project-spring.1
Labels: approved, lgtm, ok-to-test, size/S

#51 fix: upgrade deps and docs
  docs/cmd/project.md
  docs/cmd/project_import.md
  docs/cmd/project_pullrequest.md
  docs/cmd/project_quickstart.md
  docs/cmd/project_spring.md
  docs/man/man1/project-import.1
  docs/man/man1/project-pullrequest.1
  docs/man/man1/project-quickstart.1
  docs/man/man1/project-spring.1
  docs/man/man1/project.1
  go.mod
  go.sum
Labels: approved, size/L

#52 fix: set input to new input if nil
  pkg/cmd/root/root.go
Labels: approved, lgtm, size/XS

#53 fix: don't modify the git organisation name
  pkg/cmd/importcmd/import.go
Labels: approved, size/XS

#65 fix: upgrade deps
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
Labels: approved, size/M

#66 fix: add better failure message if we cannot find the dev environment
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
Labels: approved, size/M

#74 fix: add test case for jx pipeline catalog
  go.mod
  go.sum
  pkg/cmd/importcmd/buildpacks.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
Labels: approved, size/M
