Repository jenkins-x-plugins/jx-project, pull requests merged in 2020-10, with the labels that each got.

#78 fix: lets move the application of the build pack to later
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
Labels: approved, size/M

#80 fix: lets apply the build pack before the cluster PR
  pkg/cmd/importcmd/buildpacks.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_integration_test.go
  pkg/cmd/importcmd/source_config_pr.go
  pkg/cmd/root/quickstart_integration_test.go
Labels: approved, size/L

#82 fix: replace 'fix' by 'chore' and include imported repository URL in PR title
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/source_config_pr.go
Labels: approved, lgtm, ok-to-test, size/XS

#87 fix: generate the Kptfile for pipeline catalogs
  docs/cmd/project.md
  docs/cmd/project_import.md
  docs/cmd/project_pullrequest.md
  docs/cmd/project_quickstart.md
  docs/cmd/project_spring.md
  pkg/cmd/importcmd/add_missing_kptfiles.go
  pkg/cmd/importcmd/buildpacks.go
  pkg/cmd/importcmd/evaluate_buildpack.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
  pkg/cmd/importcmd/test_data/import_projects/maven_custom_build_pack/Dockerfile
  pkg/cmd/importcmd/test_data/import_projects/maven_custom_build_pack/charts/maven-custom-build-pack/Chart.yaml
Labels: approved, lgtm, size/L

#88 chore: upgrade and align with kubernetes dependencies 0.19.2, also update to go 1.15
  go.mod
  go.sum
  jenkins-x.yml
  pkg/cache/cache.go
  pkg/cmd/importcmd/add_missing_kptfiles.go
  pkg/cmd/importcmd/buildpacks.go
  pkg/cmd/importcmd/evaluate_buildpack.go
  pkg/cmd/importcmd/gitops_repo.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_deploy_integration_test.go
  pkg/cmd/importcmd/import_github_action_integration_test.go
  pkg/cmd/importcmd/import_gitops_repo_test.go
  pkg/cmd/importcmd/import_golang_integration_test.go
  pkg/cmd/importcmd/import_integration_test.go
  pkg/cmd/importcmd/import_placehoders_test.go
  pkg/cmd/importcmd/import_reporter.go
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
  pkg/cmd/importcmd/import_test.go
  pkg/cmd/importcmd/input.go
  pkg/cmd/importcmd/pack.go
  pkg/cmd/importcmd/source_config_pr.go
  pkg/cmd/root/helpers.go
  pkg/cmd/root/pullrequest/create_pullrequest.go
  pkg/cmd/root/quickstart.go
  pkg/cmd/root/root.go
  pkg/cmd/root/spring.go
  pkg/cmd/root/version/version.go
  pkg/cmd/testimports/fakes.go
  pkg/config/project_config.go
  pkg/config/project_config_test.go
  pkg/draft/draft.go
  pkg/gitresolver/buildpack.go
  pkg/gitresolver/buildpack_test.go
  pkg/jenkinsfile/modules.go
  pkg/jenkinsfile/pipeline.go
  pkg/maven/archetype.go
  pkg/maven/cli.go
  pkg/quickstarts/load.go
  pkg/quickstarts/load_test.go
  pkg/quickstarts/model.go
  pkg/spring/model.go
  pkg/statement/jenkinsfile_writer.go
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/XXL

#90 fix: lets patch up jenkins-x.yml to use older build pack
  pkg/cmd/importcmd/import.go
Labels: approved, size/S

#99 fix: upgrade dependencies
  go.mod
  go.sum
Labels: approved, size/L

#101 fix: sanitize git URL before using it in PRs/comments
  go.mod
  go.sum
  pkg/cmd/importcmd/add_collabotor.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_gitops_repo_test.go
  pkg/cmd/importcmd/import_golang_integration_test.go
  pkg/cmd/importcmd/import_integration_test.go
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
  pkg/cmd/importcmd/source_config_pr.go
  pkg/cmd/root/quickstart.go
  pkg/cmd/root/quickstart_integration_test.go
  pkg/cmd/root/root.go
  pkg/cmd/testimports/fakes.go
Labels: approved, size/L

#103 fix: add support for lazily populating git creds
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
Labels: approved, size/L

#102 fix: projectname defaults to n on import
  pkg/cmd/importcmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#118 fix: improve dryrun
  pkg/cmd/importcmd/import.go
Labels: approved, size/S

#123 fix: in dry run lets still commit spring boot changes
  pkg/cmd/importcmd/import.go
Labels: size/M

#132 fix: conventional commit messages
  pkg/cmd/importcmd/import.go
  pkg/gitresolver/buildpack_test.go
Labels: approved, lgtm, ok-to-test, size/S
