Repository jenkins-x-plugins/jx-project, pull requests merged in 2020-11, with the labels that each got.

#136 fix: lets add a promote label
  go.mod
  go.sum
  pkg/cmd/importcmd/source_config_pr.go
Labels: approved, size/L

#137 fix: disable auto merge
  pkg/cmd/importcmd/source_config_pr.go
Labels: approved, size/XS

#138 fix: upgrade to handle promote PRs on main branch
  go.mod
  go.sum
  pkg/cmd/importcmd/source_config_pr.go
Labels: approved, size/S

#139 fix: upgrade promote
  go.mod
  go.sum
Labels: approved, size/M

#140 fix: upgrade jx-promote
  go.mod
  go.sum
Labels: approved, size/XS

#142 chore: upgrade deps
  go.mod
  go.sum
Labels: size/XS

#145 fix: don't pass in a git token to create quickstart if not github.com
  pkg/cmd/root/quickstart.go
Labels: approved, size/XS

#146 fix: improve comments on PR
  go.mod
  go.sum
  pkg/cmd/importcmd/source_config_pr.go
Labels: approved, size/M

#147 fix: upgrade promote
  go.mod
  go.sum
Labels: approved, size/M

#152 fix: add a new extensions/quickstart.yaml and versionStream/quickstart.yaml
  Makefile
  docs/cmd/project.md
  docs/cmd/project_import.md
  docs/cmd/project_pullrequest.md
  docs/cmd/project_quickstart.md
  docs/cmd/project_spring.md
  docs/config.md
  docs/man/man1/project-import.1
  docs/man/man1/project-quickstart.1
  docs/man/man1/project-spring.1
  go.mod
  go.sum
  hack/configdocs/config.json
  hack/configdocs/templates/.gitignore
  hack/configdocs/templates/members.tpl
  hack/configdocs/templates/pkg.tpl
  hack/configdocs/templates/type.tpl
  pkg/apis/project/v1alpha1/constants.go
  pkg/apis/project/v1alpha1/doc.go
  pkg/apis/project/v1alpha1/pipeline_catalog_types.go
  pkg/apis/project/v1alpha1/quickstart_types.go
  pkg/cmd/importcmd/buildpacks.go
  pkg/cmd/importcmd/import_golang_integration_test.go
  pkg/cmd/testimports/fakes.go
  pkg/matcher/matcher.go
  pkg/quickstarts/load.go
  pkg/quickstarts/load_test.go
  pkg/quickstarts/model.go
  pkg/quickstarts/test_data/override/extensions/quickstarts.yaml
  pkg/quickstarts/test_data/override/versionStream/quickstarts.yaml
  pkg/quickstarts/test_data/quickstarts/versionStream/quickstarts.yaml
Labels: approved, size/XXL

#161 fix: better defaults when trying to find boot secret
  pkg/cmd/importcmd/add_collabotor.go
Labels: approved, size/XS

#157 refactor: disable flags not used for v3
  docs/cmd/project.md
  docs/cmd/project_import.md
  docs/cmd/project_pullrequest.md
  docs/cmd/project_quickstart.md
  docs/cmd/project_spring.md
  docs/config.md
  docs/man/man1/project-import.1
  docs/man/man1/project-quickstart.1
  docs/man/man1/project-spring.1
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/pick_destination.go
Labels: approved, lgtm, size/L

#167 fix: properly detect a v3 remote cluster
  go.mod
  go.sum
  pkg/cmd/importcmd/gitops_repo.go
Labels: approved, size/M

#170 fix: lets make sure we don't have empty poll period
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
Labels: approved, size/M
