Repository jenkins-x-plugins/jx-project, pull requests merged in 2020-12, with the labels that each got.

#184 refactor: remove old v2 requirements
  go.mod
  go.sum
  pkg/cmd/importcmd/buildpacks.go
  pkg/cmd/importcmd/gitops_repo.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_deploy_integration_test.go
  pkg/cmd/importcmd/import_github_action_integration_test.go
  pkg/cmd/importcmd/import_gitops_repo_test.go
  pkg/cmd/importcmd/import_integration_test.go
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
  pkg/cmd/testimports/fakes.go
  pkg/quickstarts/load.go
  pkg/quickstarts/load_test.go
Labels: approved, size/XXL

#188 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/XL, updatebot

#197 fix: better git clone for pipeline catalogs
  go.mod
  go.sum
  pkg/apis/project/v1alpha1/pipeline_catalog_types.go
  pkg/cmd/importcmd/buildpacks.go
  pkg/gitresolver/buildpack.go
Labels: approved, size/XXL

#212 Update error message on git failure
  pkg/cmd/importcmd/input.go
Labels: approved, lgtm, ok-to-test, size/XS

#217 fix: allow quickstart auth mechanism to be configured
  go.mod
  go.sum
  pkg/cmd/importcmd/buildpacks.go
  pkg/cmd/importcmd/evaluate_buildpack.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_integration_test.go
  pkg/cmd/importcmd/import_jenkinsfile_integration_test.go
  pkg/cmd/importcmd/import_test.go
  pkg/cmd/importcmd/pick_destination.go
  pkg/cmd/importcmd/source_config_pr.go
  pkg/cmd/root/quickstart.go
  pkg/cmd/testimports/fakes.go
  pkg/jenkinsutil/client.go
  pkg/jenkinsutil/constants.go
  pkg/jenkinsutil/discovery.go
  pkg/jenkinsutil/jenkinsutil.go
  pkg/jenkinsutil/server.go
Labels: approved, size/XL

#219 fix: polish the logic when importing Jenkinsfiles
  docs/cmd/project.md
  docs/cmd/project_import.md
  docs/cmd/project_pullrequest.md
  docs/cmd/project_quickstart.md
  docs/cmd/project_spring.md
  docs/config.md
  docs/man/man1/project-import.1
  docs/man/man1/project-pullrequest.1
  docs/man/man1/project-quickstart.1
  docs/man/man1/project-spring.1
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/pick_destination.go
  pkg/cmd/root/pullrequest/create_pullrequest.go
Labels: approved, size/L

#221 fix: improve the UX when using jenkinsfiles
  go.mod
  go.sum
  pkg/apis/project/v1alpha1/constants.go
  pkg/apis/project/v1alpha1/doc.go
  pkg/apis/project/v1alpha1/quickstart_types.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/pick_destination.go
  pkg/cmd/importcmd/source_config_pr.go
  pkg/quickstarts/load.go
  pkg/quickstarts/model.go
Labels: approved, size/L

#222 fix: properly pass the git token to private quickstarts if the domains match
  pkg/cmd/root/domain_cmp.go
  pkg/cmd/root/domain_cmp_test.go
  pkg/cmd/root/quickstart.go
Labels: approved, size/M

#225 chore: polish the console output a little more
  go.mod
  go.sum
  pkg/cmd/importcmd/gitops_repo.go
  pkg/cmd/importcmd/pick_destination.go
  pkg/cmd/importcmd/source_config_pr.go
Labels: approved, size/M

#226 fix: polish output and update deps
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_reporter.go
Labels: approved, size/S
