Repository jenkins-x-plugins/jx-project, pull requests merged in 2021-05, with the labels that each got.

#429 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#430 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#431 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#432 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#433 feat: Upgrade MLOps support for v3 compatibility
  README.md
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
  pkg/cmd/root/mlquickstart.go
  pkg/cmd/root/mlquickstart_integration_test.go
  pkg/cmd/root/root.go
  pkg/cmd/testimports/fakes.go
  pkg/quickstarts/load.go
Labels: approved, ok-to-test, size/L

#435 fix: add test and fix for handling repos with bad characters
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_bad_name_integration_test.go
  pkg/cmd/importcmd/test_data/import_projects/docker_slave_18.04/main.go
Labels: approved, size/L

#436 fix: migrate to helm 3
  go.mod
  go.sum
  pkg/cmd/importcmd/pack.go
  pkg/cmd/importcmd/test_data/import_projects/maven_custom_build_pack/charts/maven-custom-build-pack/Chart.yaml
Labels: approved, size/M
