Repository jenkins-x-plugins/jx-project, pull requests merged in 2021-07, with the labels that each got.

#443 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#444 fix: avoid master branch
  pkg/cmd/importcmd/import.go
Labels: approved, size/XS

#441 fix(import): placeholders test for values.yaml with comments
  pkg/cmd/importcmd/import_placehoders_test.go
  pkg/cmd/importcmd/test_data/replace_placeholders/dir3/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#445 fix: preserve comments in values.yaml from paks
  go.mod
  go.sum
  pkg/cmd/importcmd/import_golang_integration_test.go
  pkg/cmd/importcmd/pack.go
  pkg/gitresolver/buildpack_test.go
Labels: approved, size/L

#446 chore: ugprade deps
  go.mod
  go.sum
Labels: approved, size/M
