Repository jenkins-x-plugins/jx-project, pull requests merged in 2021-01, with the labels that each got.

#240 Gitea dont use invitation api
  .gitignore
  pkg/cmd/importcmd/add_collabotor.go
Labels: approved, lgtm, ok-to-test, size/XS

#252 chore: upgrade dependencies
  go.mod
  go.sum
  pkg/cmd/importcmd/import.go
Labels: approved, size/L

#255 fix: latest jx-promote requires labels on the PullRequestDetails
  go.mod
  go.sum
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
  pkg/cmd/importcmd/source_config_pr.go
Labels: approved, size/M

#254 feat: updated existing repository check logic to support more vendors
  go.mod
  go.sum
  pkg/cmd/importcmd/input.go
  pkg/cmd/importcmd/input_test.go
Labels: approved, ok-to-test, size/L

#259 fix: ugprade deps
  go.mod
  go.sum
Labels: approved, size/S

#261 chore: update go-scm dependency
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/S

#262 fix: ugprade deps
  go.mod
  go.sum
Labels: approved, size/S

#282 fix: ugprade deps
  go.mod
  go.sum
  pkg/cmd/root/pullrequest/create_pullrequest.go
Labels: approved, size/XL

#301 fix: avoid creating Kptfile if a pipeline has uses:
  go.mod
  go.sum
  pkg/cmd/importcmd/add_missing_kptfiles.go
  pkg/cmd/importcmd/add_missing_kptfiles_test.go
  pkg/cmd/importcmd/test_data/check_for_uses/kpt/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/importcmd/test_data/check_for_uses/kpt/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/importcmd/test_data/check_for_uses/kpt/.lighthouse/jenkins-x/triggers.yaml
  pkg/cmd/importcmd/test_data/check_for_uses/uses/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/importcmd/test_data/check_for_uses/uses/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/importcmd/test_data/check_for_uses/uses/.lighthouse/jenkins-x/triggers.yaml
Labels: approved, size/XL

#298 Fix the grammar errors
  pkg/cmd/importcmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#303 chore: ugprade deps
  go.mod
  go.sum
  pkg/cmd/importcmd/add_missing_kptfiles.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
  pkg/cmd/root/pullrequest/create_pullrequest.go
Labels: approved

#302 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/L, updatebot

#305 chore: ugprade deps
  go.mod
  go.sum
Labels: approved, size/S

#306 chore: fix release pipeline
  .jx/updatebot.yaml
  .lighthouse/jenkins-x/release.yaml
  promote.sh
Labels: size/M

#313 fix: add new command to enable pipelines
  Makefile
  docs/cmd/project.md
  docs/cmd/project_enable.md
  docs/cmd/project_import.md
  docs/cmd/project_pullrequest.md
  docs/cmd/project_quickstart.md
  docs/cmd/project_spring.md
  docs/man/man1/project-enable.1
  docs/man/man1/project.1
  go.mod
  go.sum
  pkg/cmd/importcmd/buildpacks.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/root/enable/enable.go
  pkg/cmd/root/root.go
Labels: approved, size/L
