Repository jenkins-x-plugins/jx-project, pull requests merged in 2022-06, with the labels that each got.

#494 chore: Update OWNERS and OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: size/S

#493 fix: add option scheduler
  docs/cmd/jx-project.md
  docs/cmd/jx-project_enable.md
  docs/cmd/jx-project_import.md
  docs/cmd/jx-project_mlquickstart.md
  docs/cmd/jx-project_pullrequest.md
  docs/cmd/jx-project_quickstart.md
  docs/cmd/jx-project_spring.md
  docs/man/man1/jx-project-import.1
  docs/man/man1/jx-project-mlquickstart.1
  docs/man/man1/jx-project-quickstart.1
  docs/man/man1/jx-project-spring.1
  pkg/cmd/importcmd/import.go
Labels: approved, size/M, ok-to-test

#499 chore: upgrade helper package to 3.2.13
  go.mod
  go.sum
  pkg/spring/model.go
Labels: approved, size/XL
