Repository jenkins-x-plugins/jx-project, pull requests merged in 2022-04, with the labels that each got.

#479 fix: bump dependency versions
  Makefile
  go.mod
  go.sum
  pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
Labels: approved, size/M

#482 Adding Makefile target for Darwin Arm64
  Makefile
Labels: size/XS, approved, lgtm, ok-to-test

#453 refactor: upgrade to go 1.17
  go.mod
  go.sum
Labels: size/L, approved
